In [54]:
from tkinter import * #tkinter is used for making the required console and the gui
from tkinter import messagebox #used for generating the messages for winning and lossing
import random #used for generating a random 2 or 4 in the empty blocks
import numpy as np
# The Board class is used for generating a nxn size board
class Board:
    #bg colour is used to set different colour for tiles of different numbers
    bg_color={

        "2": "red",
        "4": "green",
        "8": "blue",
        "16": "cyan",
        "32": "#655D8A",
        "64": "magenta",
        "128": "#1572A1",
        "256": "#9C0F48",
        "512": "#470D21",
        "1024": "#E60965",
        "2048": "#876445",
    }
    color={
         '2': 'white',
        '4': 'white',
        '8': 'white',
        '16': 'white',
        '32': 'white',
        '64': 'white',
        '128': 'white',
        '256': 'white',
        '512': 'white',
        '1024': 'white',
        '2048': 'white',
    }
    
    def __init__(self, n=4):
        self.n = n
        self.window = Tk()
        self.window.title("Ather 2048 Game")
        self.gameArea = Frame(self.window, bg = "#C7B198")
        self.board = []
        self.gridCell = np.array([[0 for i in range(self.n)]for i in range(self.n)])
        self.merge = False
        self.moved = False
        self.score = 0
        
        for i in range(self.n):
            r = []
            for j in range(self.n):
                label = Label(self.gameArea, text = "", bg = "#D06224")
                font = ("Helvetica",36,"bold")
                label.grid(row = i, column = j, padx = 5, pady = 5)
                r.append(label)
            self.board.append(r)
        self.gameArea.grid()
    
    def reverse(self):
        self.gridCell = np.flip(self.gridCell, axis = 1)

    def transpose(self):
        self.gridCell= np.transpose(self.gridCell)
    
    def compress(self):
        for i in range(self.n):
            k = self.gridCell[i]
            k = k[k!=0]
            k = np.pad(k, (0,self.n-len(k)))
            self.gridCell[i] = k
    
    def merge(self):
        self.m = False
        for i in range(self.n):
            for j in range(self.n):
                if self.gridCell[i][j] == self.gridCell[i][j+1] !=0:
                    self.gridCell[i][j] *= 2
                    self.gridCell[i][j+1] = 0
                    self.m = True
    
                    
        
game = Board()

    
    

In [123]:
import numpy as np
a = np.array([[1,0,3],
    [4,5,6],
    [7,0,0]])
print(np.where(a == 0)[0])

for i in range(3):
    k = a[i]
    k = k[k!=0]
    k = np.pad(k, (0,3-len(k)))
    a[i] = k
print(a)

[0 2 2]
[[1 3 0]
 [4 5 6]
 [7 0 0]]


In [69]:
a = 1
b =1
c=2
if a==b!=c:
    print("k")

k
